#455217 [C#テキスト]1章演習問題
kurosu-being/TextC pull request #1
Opened 2023-10-13 06:16 UTC by kurosu-being

2023-10-13 10:28 UTC, k-miyahara-being requested changes
問1-1、1-2のレビューをしました。
修正してみてください。

2023-10-13 10:28 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Program.cs
> +using Henkou;
不要なusingは消しておきましょう。
（文字色がグレーになっているものが、使われていないことを表しています。）

ショートカットキー(Ctrl + K, Ctrl + D)で、開いているファイル全体のコード整形を自動でやってくれます。
使われていないusingは自動でまとめて削除してくれたり、ずれているインデントがあったら修正してくれたりします。
とにかく見た目をきれいにしてくれる機能と思ってくれたらよいです。
コードを書ききったタイミングで毎回やる癖がついていると、きれいなコードを保つことができます！
見た目がきれいなコードを書くことも意識してみてください。

ちなみに、選択範囲だけコード整形したいときは、(Ctrl + K, Ctrl + F)を使用します。

2023-10-13 10:28 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Program.cs
> +            Product dorayaki = new Product(98, "どら焼き", 210);
dorayaki はローカル変数なので、コーディング規約にあてはめて書き換えてみてください。

2023-10-13 10:28 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        public int Price{ get; set;}
クラス、プロパティにそれぞれヘッダーコメントを付けてみてください。
1つ上の行で`///`と入力するとヘッダーコメントが現れるので、そのクラス、プロパティが何を表すものなのかを日本語で補足してください。
プロパティの説明は、今書いてあるような感じでOKです！
ヘッダーコメントを付けると↓みたいになります。
```
/// <summary>
/// 商品コード
/// </summary>
public int Code { get; private set; }
```

ヘッダーコメントがあると、第三者が見たときに、どのクラス、プロパティを使えば良いか適切に判断できるようになります。
またVisual Studioの機能として、クラス名、プロパティ名にマウスホバーしたとき、ヘッダーコメントに書いた説明が見れるようになるので、わざわざ定義に移動しなくて済み便利になります。

ほかに、publicなメソッドにもヘッダーコメントをつけるようにしてください。


参考：[Wiki>コーディング規約>コメント](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88)

2023-10-13 10:28 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        }
コメントと処理の中身が一致していませんね
実際の処理では、消費税率が10%になっています。

2023-10-13 10:28 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Program.cs
> +            Console.WriteLine("消費税額は" + dorayaki.GetTax());
単位もつけて出力してみてください！

2023-10-13 10:39 UTC, k-miyahara-being requested changes
問2-1のレビューをしました。
大体OKです！

2023-10-13 10:39 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.2-1/Program.cs
> +        //Practice1.2-1　MyClassとMyStructの2つの方を引数にとるメソッドPrintObjectsを定義してください。PrintObjectsメソッドでは、2つのオブジェクトの内容（プロパティの値)をコンソールに表示するようにしてください。なお、PrintObjectsメソッドはProgramクラスのメソッドとして定義してください。
方→型ですね😁

2023-10-13 10:39 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.2-1/Program.cs
> +    }
細かいですが、
メソッド間(16, 17行目の間)は空行を入れると見通しがよくなります。
また、20行目や22行目の空行は不要なので削除しておいてください。

2023-10-13 11:14 UTC, k-miyahara-being requested changes
問3-1のレビューをしました。

2023-10-13 11:14 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.1-3/Program.cs
このファイルは必要ですか？
必要なければ削除してください。

2023-10-13 11:14 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Student.cs
> +    }
Studentクラスにコンストラクタを実装して、そこでプロパティを設定するようにしてみてください。

2023-10-13 11:14 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-1/Program.cs
> +            Console.WriteLine("{0}は、{1}年{2}組に所属しています",student.Name, student.Grade, student.ClassNumber);
`"{0}は、{1}年{2}組に所属しています",student.Name, student.Grade, student.ClassNumber`
この部分を、文字列補間式で書き換えてみてください。
参考：https://csharp.keicode.com/basic/string-interpolation.php

2023-10-16 03:59 UTC, m-hotta-being requested changes
ちょろっと見てみました。
ファイル名については早いうちに知っておいたほうがよいと思うので、参考につけたリンク先の記事も読んでみてください。

2023-10-16 03:59 UTC, m-hotta-being commented on 章末問題第1章/Practice1.2-1/Practice1.2-1,1.2-2.csproj
> /Practice1.2-1/Priactice1.2-1,1.2-2.csproj

一般的に、ファイル名に `.` や `,` などを使用するのはオススメしません。
無用なトラブルを避けるためです。
参考： <https://ascii.jp/elem/000/004/030/4030753/>

私なら次のようにするかなぁ。
> /Practice1-2-1/Practice1-2-1_1-2-2.csproj

2023-10-16 03:59 UTC, m-hotta-being commented on 章末問題第1章/章末問題第1章/Program1.1.cs
> +using System;
using の並び順が逆ですね。
参考：[コーディング規約 - using](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#using)

2023-10-16 03:59 UTC, m-hotta-being commented on 章末問題第1章/章末問題第1章/Program1.1.cs
> +        //Productクラスが属する名前空間を別の名前空間に変更し、Mainメソッドから呼び出すようにしてください。ただし、MainメソッドのあるProgramクラスの名前空間はそのままとしてください。
【修正不要。コメントです。】
コメントには次のように `/* */` で囲うスタイルもあります。
あまり使わないと思いますが、覚えておいて損はないと思います。
```
/*
コメント
*/
```

2023-10-16 23:49 UTC, s-morita-being reviewed
研修お疲れ様です。
少し見て気になったところをコメントしました。
ご参考まで。

2023-10-16 23:49 UTC, s-morita-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +            return (int)(Price * 0.1);
演習問題を見てませんが、実際のお金の計算では端数をどう扱うかが決まっているはずなので、それに合わせた丸めをする必要があります。
`Price` が 15 円の場合の消費税は? 14 円の場合は? 16 円の場合は?
みたいな。

2023-10-16 23:49 UTC, s-morita-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        public int Price { get; set; }
コンストラクタで初期化したら変更されないプロパティの場合は `get;` だけでよいです。

各フィールド/プロパティの定義を考えるときに、
一度決めたら変更されないものなのか、後から変更できるのか、第三者が変更できるのか、
などを意識するとよいです。

後から変更できるものをなるべく少なくして、変更する方法も制限できると、
壊れにくいプログラムにしやすいと思います。

2023-10-17 01:00 UTC, kurosu-being commented on 章末問題第1章/Practice1.2-1/Practice1.2-1,1.2-2.csproj
ご指摘ありがとうございました！
参考URL、とても勉強になりました。分かりやすいファイル名の名付けを心がけたいと思います。

2023-10-17 01:06 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Program1.1.cs
> +using System;
ご指摘ありがとうございました！
コーディング規約通り.NET標のSystemを一番上に変更しました。

2023-10-17 01:10 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Program1.1.cs
> +        //Productクラスが属する名前空間を別の名前空間に変更し、Mainメソッドから呼び出すようにしてください。ただし、MainメソッドのあるProgramクラスの名前空間はそのままとしてください。
勉強になります！
上と下で挟むコメントで統一出来るという点で分かりやすいですね。
ありがとうございます！

2023-10-17 02:33 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +            return (int)(Price * 0.1);
ご指摘ありがとうございます！
演習問題では特に指定はありませんでしたが確かに、小数点以下の処理が必要だと思います。
Math.roundメソッドで小数点以下を四捨五入して返すように変更いたしました。

2023-10-17 02:40 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        public int Price { get; set; }
ご指摘ありがとうございます！
壊れにくいプログラムというお話を改めて宮原さんに解説して頂き、商品を作る為のコーディング
では必ず必要な考え方だととても勉強になりました。
フィールドやプロパティの定義する時、後から変更するのかしないのかという観点でも考える癖をつけたいと思います。

2023-10-17 02:51 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        public int Price { get; set; }
ご指摘ありがとうございます！
商品コードは一度決めたら変更しないプロパティと判断し、private set; を削除しました。

壊れにくいプログラムというお話を改めて宮原さんに解説して頂き、商品を作る為のコーディング
では必ず必要な考え方だととても勉強になりました。

2023-10-20 01:04 UTC, closed without merging