#462103 [C#テキスト]11章演習問題
kurosu-being/TextC pull request #12
Opened 2023-12-05 03:02 UTC by kurosu-being

第11章 XMLファイルの操作

主にLINQ to XMLを使ったXMLファイルの操作を学習しました。
また、XMLファイルのフォーマットについての学習も行いました。

2023-12-12 02:12 UTC, k-miyahara-being requested changes

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-1/Program11-1-1.cs
> +                var wXTeamMember = wGameName.Element("teammembers");
このあたり、明示的な型を使用しましょう。
ただし変数なくても良いかもです

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-1/Program11-1-1.cs
> +            foreach (var wGameName in wXdocument.Root.Elements()) {
wGameNameについて変数名を再度考えてみてください。
ループしているのは、「競技名」ではなく「競技」もしくは「球技」ですね。

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-2/Program11-1-2.cs
> +            Console.WriteLine("最初にプレーされた年の若い順に漢字の表記名を表示します");
同じことを最初に言っているので、このメッセージは冗長かなと思います。

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-2/Program11-1-2.cs
> +                Console.WriteLine($"漢字表記名「{wXAttribute?.Value}」");
しっかりnullチェックされてますね！
たしかに、漢字属性がない場合nullとなります。

では、nullまたは空のときは「なし」と表示されるようにしてみてください。
nullなどの異常値を判定するときは、実際そのチェックにかかった時どうするか、まで考えると良いです。

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-4/Program11-1-4.cs
> +            wOption.SetElementValue("kanji", "蹴球");
kanjiは属性ですが、要素として追加されてしまっています。

XEmelemtのコンストラクタのオーバーロードなどをみてみるとよいです。

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-1-4/Program11-1-4.cs
> +            var wOutputFile = Path.Combine(Path.GetDirectoryName(wInputFile), wOutputFileName + ".xml");
入力したファイル名に拡張子(.xml)が既についているならそのまま、
ついていないなら拡張子を付ける、という風に実装してみてください。

エクスプローラでファイル保存するときは、↑のような動きになっています。

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-2-1/Program11-2-1.cs
> +                foreach (var wOrdElement in wDocument.Descendants("word")) {
wOrdElement 誤字ですかね？
接頭辞wとwordがかぶった？😂

2023-12-12 02:12 UTC, k-miyahara-being commented on 章末問題11/Practice11-2-1/Program11-2-1.cs
> +                    return;
拡張子には"."が必要です。
`"xml"` → `".xml"`

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-1/Program11-1-1.cs
> +                var wXTeamMember = wGameName.Element("teammembers");
ご指摘ありがとうございます。
不要な変数を削除し、明示的な型を使用して修正しました。

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-1/Program11-1-1.cs
> +            foreach (var wGameName in wXdocument.Root.Elements()) {
ご指摘ありがとうございます。
ループしているものを正しく示すように変数名を変更しました。（wGameName→wGame)

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-2/Program11-1-2.cs
> +            Console.WriteLine("最初にプレーされた年の若い順に漢字の表記名を表示します");
ご指摘ありがとうございます。
メッセージを削除しました。

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-2/Program11-1-2.cs
> +                Console.WriteLine($"漢字表記名「{wXAttribute?.Value}」");
ありがとうございます！

null、または空の時は「なし」と表示されるように変更いたしました。

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-4/Program11-1-4.cs
> +            wOption.SetElementValue("kanji", "蹴球");
ご指摘ありがとうございます。
kanjiが属性として追加されるよう、修正いたしました。

2024-02-02 08:05 UTC, kurosu-being commented on 章末問題11/Practice11-1-4/Program11-1-4.cs
> +            var wOutputFile = Path.Combine(Path.GetDirectoryName(wInputFile), wOutputFileName + ".xml");
> 入力したファイル名に拡張子(.xml)が既についているならそのまま、
> ついていないなら拡張子を付ける、という風に実装してみてください。

そのような挙動になるよう機能を追加しました。
エクスプローラーもこのような形になっていることを初めて知りました😲

2024-02-02 08:06 UTC, kurosu-being commented on 章末問題11/Practice11-2-1/Program11-2-1.cs
> +                foreach (var wOrdElement in wDocument.Descendants("word")) {
被りました😭
ご指摘ありがとうございます。修正いたしました。

2024-02-02 08:06 UTC, kurosu-being commented on 章末問題11/Practice11-2-1/Program11-2-1.cs
> +                    return;
ご指摘ありがとうございます。
修正いたしました。

2024-02-05 02:32 UTC, merged