#463298 [C#テキスト]12章演習問題
kurosu-being/TextC pull request #13
Opened 2023-12-11 09:07 UTC by kurosu-being

第12章 シリアル化、逆シリアル化

主にシリアル化、逆シリアル化について学習し、JSONファイルやXMLファイルについて学習しました。

2023-12-22 00:24 UTC, ohdaira-being requested changes
少しコメントしました。

2023-12-22 00:59 UTC, ohdaira-being requested changes

2023-12-22 00:59 UTC, ohdaira-being commented on 章末問題12/Practice12-1-2/Program12-1-2.cs
> +            };
オブジェクト初期化子でのインスタンス初期化を複数行っています。
同じインスタンス初期化が複数あるなら、コンストラクタを用意したほうが便利かつミスがなくなりそうです。
コンストラクタを定義して、それを使ってインスタンス初期化するようにしてください。

2023-12-22 00:59 UTC, ohdaira-being commented on 章末問題12/Practice12-1-3/Program12-1-3.cs
> +                Employee[] wEmployees = wSerializer.ReadObject(wReader) as Employee[];
右辺から型が明らかですので、暗黙的な型宣言にしてください。

2023-12-22 00:59 UTC, ohdaira-being commented on 章末問題12/Practice12-1-4/Program12-1-4.cs
> +            };
コンストラクタを活用してください。

2023-12-22 00:59 UTC, ohdaira-being commented on 章末問題12/Practice12-2-2/Program12-2-2.cs
> +            };
設定がデフォルトになっています。
何も設定しないなら、変数として管理する必要はないかと思いますので、
変数で宣言せずに使うときにインスタンス生成するようにしてください。

2024-02-05 06:05 UTC, kurosu-being commented
@ohdaira-being 
レビュー頂きありがとうございました！
お待たせしておりました、ご確認ください。

2024-02-05 06:05 UTC, kurosu-being commented on 章末問題12/Practice12-2-2/Program12-2-2.cs
> +            };
ご指摘ありがとうございます。
変数で管理せず、直接インスタンスを生成してシリアライズするように変更いたしました。

2024-02-05 06:05 UTC, kurosu-being commented on 章末問題12/Practice12-1-4/Program12-1-4.cs
> +            };
ご指摘ありがとうございます。
コンストラクタを実装し、修正いたしました。

2024-02-05 06:05 UTC, kurosu-being commented on 章末問題12/Practice12-1-3/Program12-1-3.cs
> +                Employee[] wEmployees = wSerializer.ReadObject(wReader) as Employee[];
ご指摘ありがとうございます。
明示的な型を使用する形に修正いたしました。

2024-02-05 06:05 UTC, kurosu-being commented on 章末問題12/Practice12-1-2/Program12-1-2.cs
> +            };
ご指摘ありがとうございます。
コンストラクタを利用して初期化が行えるように実装しました。

2024-02-05 06:34 UTC, merged