#463772 [C#テキスト]12章演習問題
kurosu-being/TextC pull request #14
Opened 2023-12-15 06:24 UTC by kurosu-being

第13 EntityFrameworkによるデータアクセス

データベース管理システムについて、Entiity FrameworkのCode Firstを利用しながら学習しました。

2023-12-27 06:28 UTC, ohdaira-being requested changes
コメントしましたので、確認してください。

また、BookとAuthorがコンストラクタを使用せずにオブジェクト初期化子を使っていて、冗長に感じます。
コンストラクタを定義し、コンストラクタを使って初期化するようにしてください。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-1~2/Models/BooksDbContext.cs
> +    //}
コメントアウトしているコード（不要なコード）は、削除するようにしてください。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
DisplayAllBooksメソッドは、すべての書籍を表示するメソッドですが、
実際に中身を見ると、GetBooksメソッドを呼んでいるため、書籍を取得して表示するメソッドになっています。
なので、コメントを修正するか引数で書籍を受け取り、受け取った書籍を表示するメソッドに修正してください。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +            foreach (var wBook in wBooks) {
wBooks は、一度しか使われていないようです。
一度しか使われない変数は、わざわざ変数で管理する必要がありません。
また、無駄にメモリを確保することになります。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
AddAuthorsメソッドは、著者を追加するメソッドですが、
このメソッドを呼ぶたびにメソッド内で初期化された著者が追加されるようになっています。
そのため、追加したい著者を変えたい場合、メソッドの中身を書き換える必要があり、使うときにとても注意が必要となっています。
汎用的に好きな著者を追加できるメソッドに修正してみてください。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
こちらも決まった書籍を追加するメソッドになっていますので、
AddAuthorsメソッドと同様に好きな書籍を追加できるように修正してみてください。

2023-12-27 06:28 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +            return vContext.Books.Where(x => x.Title.Length == wMaxLength).ToList();
ToList()が可読性を下げ、不要なメモリの確保を行っています。
削除するかメソッドの戻り値の型とメソッド名の修正、のどちらかを行ってください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +    }
引数に関するコメントが抜けています。
また、BooksDbContext を引数で受け取るのは大きすぎると思います。
このメソッド内で必要な最小限のものを受け取るように修正してください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +            return vContext.Books.OrderBy(x => x.PublishedYear).Take(3).ToList();
上記と同様にこちらのToList()も修正してください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +            return vContext.Books.Where(x => x.Title.Length == wMaxLength).ToList();
上記と同様にこちらのToList()も修正してください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        }
最小限の型を受け取るように引数を修正してください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +    }
最小限の型を受け取るように引数を修正してください。

2023-12-27 06:28 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +        }
実行してみたところ、group.Keyがnullとなりnull参照例外が起きました。
再度、考え直してみてください。
また、groupではなくyを使ってください。x,y,zの順に使われます。

2024-02-05 06:09 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Models/BooksDbContext.cs
> +    //}
ご指摘ありがとうございます。
削除いたしました。

2024-02-05 06:10 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
ご指摘ありがとうございます。
引数で書籍を受け取り、受け取った書籍を表示するメソッドとして修正しました。また、メソッド名をDisplayBooksと変更しました。

2024-02-05 06:10 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +            foreach (var wBook in wBooks) {
ご指摘ありがとうございます。
不要な変数を削除いたしました。

2024-02-05 06:12 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
ご指摘ありがとうございます。
汎用的なものになるよう、リストを受け取り加えるメソッドになるよう修正し、
Mainメソッドで追加リストを追加するように書き換えました。

2024-02-05 06:12 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        }
ご指摘ありがとうございます。
同様に修正いたしました。

2024-02-05 06:13 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +            return vContext.Books.Where(x => x.Title.Length == wMaxLength).ToList();
ご指摘ありがとうございます。
ToList()を削除いたしました。

2024-02-05 06:14 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +    }
ご指摘ありがとうございます。
引数に対するコメントを追記し、受け取る型をIEnumerable<Book>に変更いたしました。

2024-02-05 06:14 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +            return vContext.Books.OrderBy(x => x.PublishedYear).Take(3).ToList();
ご指摘ありがとうございます。
同様に修正いたしました。

2024-02-05 06:15 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +            return vContext.Books.Where(x => x.Title.Length == wMaxLength).ToList();
ご指摘ありがとうございます。
こちらも同様に、ToList()を削除する形で修正しました。

2024-02-05 06:15 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        }
ご指摘ありがとうございます。
BooksDbContext →IEnumerable<Book>に型を変更致しました。

2024-02-05 06:16 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +    }
ご指摘ありがとうございます。
同様に、BooksDbContext →IEnumerableに型を変更致しました。

2024-02-05 06:17 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +        }
ご指摘ありがとうございます。
group.Keyがnullの時（一度も書籍の追加を行っていないとき）「コレクションが存在しません」と表記されるよう
修正いたしました。
また、groupではなくyを使用して修正いたしました。

2024-02-09 05:35 UTC, ohdaira-being reviewed
再度、コメントしました。
コーディング規約に関する些細な指摘ばかりですが、修正お願いします。
コーディング規約に慣れていきましょう！

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
コーディング規約（引数名：先頭にvを付ける。例：vAuthor）に沿って、書き換えてください。
他のメソッドも確認してください

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +                wDbContext.Authors.RemoveRange(wAllAuthors);
`wAllBooks`と`wAllAuthors`が一度しか使われていないので、変数でもつ必要がないと思います。
1度しか使われない変数は、必要な場合もありますが、基本的には宣言しません。
不要な変数を宣言しないように修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
引数名をコーディング規約に沿って修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +                                    .ToList();
ToList()で不要にメモリを確保しているので、削除しましょう。
同時にしたのif条件式も修正してください。

2024-02-09 05:35 UTC, ohdaira-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +                           .OrderByDescending(group => group.Key.Birthday);
こちらもコーディング規約に沿って、xyzの順に使うようにしましょう

2024-02-09 07:29 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
ご指摘ありがとうございます。
修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-1~2/Program13-1-1~13-1-2.cs
> +                wDbContext.Authors.RemoveRange(wAllAuthors);
ご指摘ありがとうございます。
不要な変数を削除し、修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:30 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:31 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-3/Program13-1-3.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:31 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        static void InsertBooks(BooksDbContext dbContext, List<Book> booksToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:31 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        static void DisplayBooks(IEnumerable<Book> books) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:31 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        private static void AddAuthors(List<Author> authorsToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:31 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-4/Program13-1-4.cs
> +        private static void AddBooks(List<Book> booksToAdd) {
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 07:32 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +                                    .ToList();
ご指摘ありがとうございます。
ToList()を削除し、次のif条件式をAny()メソッドで検索するように修正しました。

2024-02-09 07:32 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +                           .OrderByDescending(group => group.Key.Birthday);
ご指摘ありがとうございます。
引数名をコーディング規約に沿って修正いたしました。

2024-02-09 08:03 UTC, ohdaira-being reviewed
1点、修正お願いします。

2024-02-09 08:03 UTC, odaira1119 commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +            if (wBooksWithAuthor.Any()) {
条件が逆転してしまいました。
正しい条件になるように修正お願いします。

2024-02-09 08:06 UTC, kurosu-being commented on 章末問題13(修正)/Practice13-1-5/Program13-1-5.cs
> +            if (wBooksWithAuthor.Any()) {
失礼しました、修正足しました。🙇‍♀️

2024-02-09 08:13 UTC, merged