455217 [C#テキスト]1章演習問題　作り直し
kurosu-being/TextC pull request #2
Opened 2023-10-16 05:36 UTC by kurosu-being

Gitでトラブルが起きたためブランチを作り直しました。

2023-10-16 06:40 UTC, k-miyahara-being requested changes
コード整形のおかげで、かなり見やすくなりました！
もう少し修正をお願いします

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Program1-1-1,1-1-2,1-1-3.cs
> +            Console.WriteLine("消費税額は" + wdorayaki.GetTax() + "円です");
接頭辞w の後は、大文字になるので、`wDorayaki` が正しいですね。
他の箇所も同様に、修正をお願いします。

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +            this.Code = code;
ヘッダーコメントの追加ありがとうございます！
`<param name="">`は、引数を表しています。
引数がそれぞれ何を指しているのか、プロパティと同様に説明を書いてみてください。

また、コーディング規約に則って、引数にも接頭辞をつけましょう！

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        /// <returns>int</returns>
`<returns>`は、戻り値を表しています。
ここには、戻り値が何を指しているかの説明を書いてください。

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Student.cs
> +        }
ヘッダーコメントについての修正漏れがあります！
指摘があった場合は、指摘箇所だけでなく他にも同様の箇所がないか見てみましょう。

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Person.cs
> +            return age;
コーディング規約を適用しましょう！

また、if文は1行にまとめてしまったほうが見やすい時があります。
今回のように、分岐した中身が`age--;` しか処理がないので、↓のように1行にまとめておきましょう。
`if (today < Birthday.AddYears(age)) age--;`

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-1/Program1-3-1,1-3-2.cs
> +            Console.WriteLine("{0}は、{1}年{2}組に所属しています", wtudent.Name, wtudent.Grade, wtudent.ClassNumber);
https://github.com/kurosu-being/TextC/pull/1#discussion_r1358123966

2023-10-16 06:40 UTC, k-miyahara-being commented on 章末問題第1章/Practice1.3-1/Student.cs
> +        }
このままだと、Studentクラスのインスタンスはすべて中身が同じになってしまいます。
引数で受け取って、各プロパティに代入する形になっているとよいですね。

2023-10-16 07:05 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Program1-1-1,1-1-2,1-1-3.cs
> +            Console.WriteLine("消費税額は" + wdorayaki.GetTax() + "円です");
ありがとうございます！コーディング規約の例をよく見ていませんでした。
修正を行いました。

2023-10-16 07:17 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +            this.Code = code;
ご指摘ありがとうございます！
コーディング規約に則って、引数に接頭辞を追加しました。
引数の説明はプロパティと同じに変更しましたが、”商品名の引数”など名前を変える方が良いでしょうか？

2023-10-16 07:17 UTC, kurosu-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +        /// <returns>int</returns>
ご指摘ありがとうございます！戻り値の説明を追加しました。

2023-10-17 00:37 UTC, kurosu-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Student.cs
> +        }
ご指摘ありがとうございます。全てのcsファイルを確認し、publicメソッド、プロパティを中心にヘッダーコメントを記入しました。

2023-10-17 00:51 UTC, kurosu-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Person.cs
> +            return age;
ご指摘ありがとうございます。
問3のPerson.csにおいて、コーディング規約に則りローカル変数の名前を
today →wToday, age → wAge に変更しました。
また、ifを一行に纏めました。

2023-10-17 01:12 UTC, kurosu-being commented on 章末問題第1章/Practice1.3-1/Program1-3-1,1-3-2.cs
> +            Console.WriteLine("{0}は、{1}年{2}組に所属しています", wtudent.Name, wtudent.Grade, wtudent.ClassNumber);
ご指摘ありがとうございます。
文字列補間式の変更がPractice1-3-3,1-3-4にしか反映しておりませんでした。
全てのcsで変更し、反映しました。

2023-10-17 01:14 UTC, kurosu-being commented on 章末問題第1章/Practice1.3-1/Student.cs
> +        }
ご指摘ありがとうございます！
引数で受け取って、各プロパティに代入する形に変更いたしました。

2023-10-17 03:50 UTC, m-hotta-being approved these changes
ちょっと見てみました。
確認してみてください。

2023-10-17 03:50 UTC, m-hotta-being commented on 章末問題第1章/Practice1.2-1/MyClass.cs
> +﻿namespace Practice1._2_1 {
【必要なら修正してください】
名前空間 (namespace) は以下のように `.` で区切ることで階層 `System` - `Collections` - `Generic` を表現できます。
```
System.Collections.Generic
```

本題ですが `Practice1._2_1` は `Practice1` - `_2_1` なのでしょうか？
`_2_1` が `_` で始まっていてあまり見ない形なので気になりました。

2023-10-17 03:50 UTC, m-hotta-being commented on 章末問題第1章/Practice1.2-1/Program1-2-1,1-2-2.cs
> +        /// <param name="vMC"></param>
惜しい！
`<param name="vMC">（ここに説明を書く）</param>` 

この形式のコメントの書き方は、このページが参考になると思います。

* [コード要素の XML コメントを挿入するには](https://learn.microsoft.com/ja-jp/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2022)

2023-10-17 03:50 UTC, m-hotta-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Person.cs
> +            if (wToday < Birthday.AddYears(wAge)) wAge--;
【修正不要。ただのコメントです。】
`--wAge` という書き方があるのは知っていますか？
もしまだ知らないなら、どう違うか一度調べてみてください。

2023-10-17 04:31 UTC, kurosu-being commented on 章末問題第1章/Practice1.2-1/Program1-2-1,1-2-2.cs
> +        /// <param name="vMC"></param>
ご指摘ありがとうございます。
修正いたしました！
頂いたURLも参考にコメントの書き方を勉強します！

2023-10-17 05:07 UTC, kurosu-being commented on 章末問題第1章/Practice1.3-3, 1.3-4/Person.cs
> +            if (wToday < Birthday.AddYears(wAge)) wAge--;
どちらに書くかで意味が違うのですね！勉強になりました、ありがとうございます！

2023-10-17 05:08 UTC, kurosu-being commented on 章末問題第1章/Practice1.2-1/MyClass.cs
> +﻿namespace Practice1._2_1 {
ご指摘ありがとうございます！
意図したものではなく、namespaceを変更すると
｛が必要です
というエラーが出てきてしまうため放置しておりました。
原因を調べてみようと思います。

2023-10-18 03:10 UTC, k-miyahara-being reviewed
あと少しです！
修正をお願いします。

2023-10-18 03:10 UTC, k-miyahara-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問１/Product.cs
> +        /// <returns>int</returns>
戻り値の説明も、他と同様にreturnsタグの間に書くようにしましょう。
`<returns>商品価格の消費税をを消費税10%で計算した値</returns>`
ほかの箇所にもあるので、確認お願いします

XMLについて：https://wa3.i-3-i.info/word1577.html

2023-10-18 03:10 UTC, k-miyahara-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問3-4/Program1-3-4.cs
> +            Console.WriteLine($"{vName}は、{vGrade}年{vClassnumber}組に所属しています");
ここは、わざわざ変数に代入する必要はないかなと思います。（コーディング規約違反でもありますね！）
`wStudent.Name`や`wStudent.Grade`は1か所でしか使用されていないからです。
メソッド内の複数箇所で使用するのであれば、書いてもらったように変数に代入して使いまわすとよいです。

2023-10-18 03:11 UTC, k-miyahara-being commented on 章末問題第1章/章末問題第1章/Product.cs
> +            this.Code = code;
> 引数の説明はプロパティと同じに変更しましたが、”商品名の引数”など名前を変える方が良いでしょうか？
これはすでに解決済みですかね？

2023-10-18 03:56 UTC, m-hotta-being commented on 章末問題第1章/Practice1.2-1/MyClass.cs
> +﻿namespace Practice1._2_1 {
> 原因を調べてみようと思います。

きっと、このページが参考になると思います。

* [C# 識別子の名前付け規則と表記規則](https://learn.microsoft.com/ja-jp/dotnet/csharp/fundamentals/coding-style/identifier-names)
  * [名前指定の規則](https://learn.microsoft.com/ja-jp/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-rules)

2023-10-18 05:13 UTC, kurosu-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問１/Product.cs
> +        /// <returns>int</returns>
ご指摘ありがとうございます！
修正を行いました。戻り値の説明も文言で説明した方が良いのですね。

2023-10-18 05:18 UTC, kurosu-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問3-4/Program1-3-4.cs
> +            Console.WriteLine($"{vName}は、{vGrade}年{vClassnumber}組に所属しています");
ご指摘ありがとうございます！
変数を直接文字列補間式に書き込む方法に変更いたしました。
一か所でしか使用しない変数について考えが及んでいませんでした。勉強になります。

2023-10-18 06:54 UTC, k-miyahara-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問3-4/Program1-3-4.cs
> +            Console.WriteLine($"{vName}は、{vGrade}年{vClassnumber}組に所属しています");
コメントアウトしたのは、コーディング規約の修正をしたことを伝えるためですかね？
そうでなければ、不要なコードは消しておきましょう！

2023-10-18 06:59 UTC, k-miyahara-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問１/Product.cs
> +        /// <returns>int</returns>
すみません、↑の例ではそのまま書いてしまいましたが、
メソッドの説明と被っている部分は冗長なのでなくてよいです。

↓みたいな感じでできるだけシンプルにしましょう。
```
/// <summary>
/// 消費税を求める（消費税率は10%）
/// </summary>
/// <returns>消費税額</returns>
```

2023-10-18 07:17 UTC, kurosu-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問3-4/Program1-3-4.cs
> +            Console.WriteLine($"{vName}は、{vGrade}年{vClassnumber}組に所属しています");
修正を伝えるつもりでしたが、ここでも伝えているので不要ですね。
消しておきます！

2023-10-18 07:28 UTC, kurosu-being commented on 章末問題第1章/演習問題第1章 remake/演習問題第1章問１/Product.cs
> +        /// <returns>int</returns>
ありがとうございます！シンプルな文言に書き換えます。

2023-10-19 01:32 UTC, k-miyahara-being approved these changes
OKです！

2023-10-19 04:45 UTC, m-hotta-being approved these changes
修正お疲れさまでした！

2023-10-19 07:50 UTC, merged