#456425 [C#テキスト]3章演習問題
kurosu-being/TextC pull request #4
Opened 2023-10-23 04:46 UTC by kurosu-being

第3章 ラムダ式とLINQの基礎

1.ラムダ式とはなにか
2.List<T>とラムダ式の組み合わせ
3.LINQ to Objectsの基礎、クエリ演算子、シーケンス
4.即時実行、遅延実行
などを学習しました。

2023-10-23 11:15 UTC, yuki-tanaka-being reviewed
ちょっと見てみました。

2023-10-23 11:15 UTC, yuki-tanaka-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            }
Console.WriteLine() を if-else の中に記載していますが、分岐の中は文字列を構築するだけにし、出力は分岐の外で扱う方が保守性が高くなります。
理由は、出力する文字列を構築する処理と、出力処理を独立させたほうが保守性が高くなるからです。
独立させた方が保守性が高くなるのは、例えば、出力方法を変更するとなった場合、今の処理だと2か所修正が必要です。
また、出力する文字列を構築する条件が増えた場合に、Console.WriteLine() をさらに追加で書く必要があり、この状態で出力処理を変更となったら3か所修正が必要になります。
このように、一つの処理で二つのことをやると、保守性が下がる恐れがあります。
```
            string wOutput = wIndex != -1 ? $"インデックス番号は {wIndex}" : "-1";
            Console.WriteLine(wOutput);
```

ただし、この課題の場合は、そもそも -1 で分岐する必要はないかなと思います。

もう1点、もし分岐する場合の条件は `wIndex != -1` ではなく、`wIndex >= 0` が好ましいです。
理由は、基本的にインデックスを扱うときは 0 以上が存在するを示し、０未満がないかとを示します。
ないときは -1 を返す仕様ですが、本質的には -2 でも -100 でもよいです。
インデックスでないを示すのは 0 未満が基本的な条件の扱い方になります。

2023-10-24 04:44 UTC, kurosu-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            }
ご指摘ありがとうございます！
ご指摘の部分を条件演算子を用いて`wIndex >= 0`の条件で分岐するように変更し、Consoleの処理を独立させました。

> このように、一つの処理で二つのことをやると、保守性が下がる恐れがあります。
確かに、1つの処理が入り組んでしまうとメンテナンスの手間もかかりますし修正の際のヒューマンエラーも誘発させますね。1つの処理＝1つのことでコードが書けるよう練習していきたいと思います👩‍🎓

2023-10-24 04:55 UTC, kurosu-being commented
第2章演習問題のブランチ(feature/chapter2)から現在の第3章演習問題のブランチを派生させてしまった関係で、
当プルリクエストに第2章の変更差分が出てしまっています。
見づらくなってしまっておりますが、ご確認よろしくお願いいたします。

2023-10-24 07:27 UTC, yuki-tanaka-being reviewed
修正ありがとうございます。
修正箇所で気になった点をレビューしました。

2023-10-24 07:27 UTC, yuki-tanaka-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            Console.WriteLine($"{wMessage}");
`wMessage` は `string` の変数なので、`Console.WriteLine` に渡すときに リテラルに変換せず、そのまま変数を渡せます。
`Console.WriteLine(wMessage);`
推測で記載しますが、もし、元のコードから変更した結果こうなっただけで、最初からこのコードを書いていたらちゃんと書けていたとするなら、
- ひとまず書き終わった後に本当にそれがベストかもう一度ちゃんと見直す
- 修正するときは手をいれる局所的な部分だけでなく周辺も考慮して最適になっているか確認するようにする

といったアクションを実施すると、そういうミスが防ぎやすいかなと思います。

2023-10-25 06:13 UTC, k-miyahara-being requested changes

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-1-1/Program3-1-1.cs
> +            Console.WriteLine(wExsits);
誤字です。`wExsits → wExists`
ただ、なくてよい変数ですね！

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-1-2/Program3-1-2.cs
> +        //List<T>のメソッドを使い、書く要素を2.0で割った値をコンソールに出力してください。
細かいですが、問題文の誤字です。
書く要素 → 各要素

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-1-3/Program3-1-3.cs
> +                Console.WriteLine(wN);
`wWhere`は不要な変数ですね。
foreach文に直接書いてしまいましょう。
`= wNumbers.Where(s => s >= 50);`の部分が異常に長く読みづらい場合は一旦変数に置いてしまうのもアリと思いますが、今回のような場合はそのまま書いてしまったほうが無難です。

`wN`について、命名し直してみましょう。
第三者がみて意味を理解しづらい変数名になってしまっています。

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-1-4/Program3-1-4.cs
> +            }
ここは問題に指定があるので、`wWhere`に格納するのは正しいです。
ですが、`wWhere`という変数名も意味が伝わらないものになってしまっているので命名し直してみましょう。

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            string wInputuser = Console.ReadLine();
`wNames`は問題指定の変数名ですが、練習として、ふさわしいものに命名し直してみましょう。
`wInputuser`は変更するとしたら`wUserInput`または単に`wInput`が良いと思いますが、なくてもよいです。

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +        //Practice3-2-1 コンソールから入力した歳名が何番目に格納されているかList<T>のFindINdexメソッドを使って調べ、その結果をコンソールに出力してください。見つからなかったら、-1を出力してください。なお、コンソールの入力にはConsole.ReadLineメソッドを利用してください。
問題文の誤字です。
歳名 → 都市名

プログラムに限ったことではありませんが、誤字は特に気を付けるようにしましょう。
ここはコメントなので影響有りませんが、例えば、画面に表示するメッセージに誤字があると、それがそのままバグとして扱われてしまいます。
もちろんテスト等で他者の目が入るのでそのままお客様のもとに届く確率は低いですが、個人の力で未然に防げるような箇所はなるべく気を付けるようにしておきましょう👍

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-2/Program3-2-2.cs
> +            var wNames = new List<string> { "Tokyo", "ONew Delhi", "Bangkok", "London", "Paris", "Berlin", "Canberra", "Hong Kong" };
> "ONew Delhi"

大文字のケースも問題ないかしっかりテスト出来てますね！Goodです。

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-3/Program3-2-3.cs
> +                Console.WriteLine(wN);
と同様です。

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wNum = wWhere.Select(s => s.Length);
文字列の先頭の文字を取得するのに、LINQをつかうこともできます。
書き換えてみてください。

また、メソッドチェーンを使って1行で書くことができます。
メソッドチェーンについては、テキストにある(?)と思うので調べてみてください。
なければネットで！

2023-10-25 06:13 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +        static void Main(string[] args) {
[追加問題]
同様に、'n' で終わる都市名を抽出し、アルファベット順にならべたものを出力してください。
※ファイルはわけなくてOKです。

2023-10-25 06:57 UTC, s-morita-being reviewed
お疲れ様です。
ひとつコメントしました。

2023-10-25 06:57 UTC, s-morita-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wWhere = wNames.Where(s => s[0] == 'B');
この例題では問題にならないので、これでよいと思いますが、
`wNames` に空文字が含まれてもよい仕様の場合、 `s` が空文字だと `s[0]` でエラーが発生します。
ご参考まで。

2023-10-26 07:17 UTC, kurosu-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            Console.WriteLine($"{wMessage}");
ご指摘ありがとうございます！直接変数を渡す形に修正いたしました。
ご推察の通り、コピー&ペーストで局部的な手入れを行っていました。アドバイス頂いた2点を、今後特に注意したいと思います。

2023-10-26 07:17 UTC, kurosu-being commented on 章末問題3/Practice3-1-1/Program3-1-1.cs
> +            Console.WriteLine(wExsits);
ご指摘ありがとうございます！変数名を修正し、不要に定義しているwExsitsを削除しました。

2023-10-26 07:18 UTC, kurosu-being commented on 章末問題3/Practice3-1-2/Program3-1-2.cs
> +        //List<T>のメソッドを使い、書く要素を2.0で割った値をコンソールに出力してください。
ご質問ありがとうございます！正しい変換に修正いたしました。

2023-10-26 07:18 UTC, kurosu-being commented on 章末問題3/Practice3-1-3/Program3-1-3.cs
> +                Console.WriteLine(wN);
ご質問ありがとうございます！
wWhereを削除し、直接書く形に変更いたしました。
また、wNについてもwResultに変更いたしました。

2023-10-26 07:21 UTC, kurosu-being commented on 章末問題3/Practice3-1-4/Program3-1-4.cs
> +            }
ご指摘ありがとうございます！
wWhere→wResultに命名を変更いたしました。

2023-10-26 07:21 UTC, kurosu-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            string wInputuser = Console.ReadLine();
ご指摘ありがとうございます！
Names→wCityNames
wInputuser→wInput
に変更いたしました。

2023-10-26 07:21 UTC, kurosu-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +        //Practice3-2-1 コンソールから入力した歳名が何番目に格納されているかList<T>のFindINdexメソッドを使って調べ、その結果をコンソールに出力してください。見つからなかったら、-1を出力してください。なお、コンソールの入力にはConsole.ReadLineメソッドを利用してください。
コードの中の確認のみで、コメントの確認を怠っていました。
今後商品に携わる為にも誤字がエラーになるということに注意して文章を書くようにします。
ご指摘ありがとうございます！

2023-10-26 07:22 UTC, kurosu-being commented on 章末問題3/Practice3-2-3/Program3-2-3.cs
> +                Console.WriteLine(wN);
ご質問ありがとうございます！
同様に修正を行いました。

2023-10-26 07:22 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wNum = wWhere.Select(s => s.Length);
ご指摘ありがとうございます！LINQのFirstOrDefaultメソッドを用いる形に変更し、メソッドチェーンを使って書き直しました。

2023-10-26 07:22 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +        static void Main(string[] args) {
ありがとうございます！追加問題を実装しました。

2023-10-26 07:23 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wWhere = wNames.Where(s => s[0] == 'B');
ご指摘ありがとうございます！
null条件演算子を用いて空文字の時nullを返すように変更いたしました。

2023-10-26 07:39 UTC, s-morita-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wWhere = wNames.Where(s => s[0] == 'B');
あ、ちょっと分かりにくい説明でした。
空文字というのは `null` ではなくて `""` のことで、↓の場合に `s[0]` でインデックスエラーが発生する。という意味でした。
```
var wNames = new List<string> { "" };
```
ので、既に修正してもらっている `s.FirstOrDefault() == 'B'` で解消しているはずです。
(`s.Length > 0 && s[0] == 'B'` でも OK です。)

逆に wNames が null になることはないので、 `?.` の `?` はない方がよいです。

文字列は `null` と空文字 `""` で違うものなので注意してください。
仕様や設計によって、両者に異なる意味が与えられていて明確に区別しないといけない時もあれば、
区別があいまいで同一扱いした方がよい時もあったりします。

2023-10-26 08:21 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wWhere = wNames.Where(s => s[0] == 'B');
ご指摘の意味を誤解しておりました、申し訳ないです🙇‍♀️
?.を削除いたしました。

先頭字（s[0]）が存在しない文字列が存在しうる　→　それが空文字 `""`ということですね。
` null` と空文字 `""`について混同して理解していた部分があったので、改めて調べようと思います。
ご指摘ありがとうございます！

2023-10-26 10:07 UTC, k-miyahara-being commented on 章末問題3/Practice3-1-4/Program3-1-4.cs
> +            }
`Result`とは「何の」結果か？がわかりづらくなってしまいます。
今回は、その変数を直後の行で使用しているので大きく問題はおこりませんが、定義された箇所から離れた場所でも使用するとすると、そのころには「何の」結果だったっけ？とコードをさかのぼる必要がでてくる可能性があります。

コードのどこからみてもわかるような命名がされていると良いでしょう。
2倍にした結果なので、`wTwiceNumbers`とかですかね。

2023-10-26 10:09 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-3/Program3-2-3.cs
> +                Console.WriteLine(wN);
リンクはるつもりが忘れてました(笑)
意図くみとっていただきありがとうございます

2023-10-26 10:16 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wNum = wWhere.Select(s => s.Length);
First()ではなくFirstOrDefault()を使用した理由を説明できますか？

2023-10-26 10:29 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +        static void Main(string[] args) {
Orderbyで、先頭文字で並べ替えしていることで、2文字目以降では比較がされず並べ替えされません。
試しに、リストの先頭に"Lyon"を追加して実行してみてください。
↓のようになり、LyonとLondonはアルファベット順としては逆になってしまっています。
```
Edmonton
Lyon
London
```

2023-10-27 04:45 UTC, kurosu-being commented on 章末問題3/Practice3-1-4/Program3-1-4.cs
> +            }
ご質問ありがとうございます。
wResult→wTwiceNumbers
wMessage→wNumber
に変更いたしました。
コードのどこからみてもわかるような命名という観点がなかったので今後気を付けていきたいと思います。

2023-10-27 04:45 UTC, kurosu-being commented on 章末問題3/Practice3-2-3/Program3-2-3.cs
> +                Console.WriteLine(wN);
ご質問ありがとうございます！
Listの名前を、wCityName→wCityNamesに変更し
wMessage→wCityNameに変更しました。
また、csファイル全体の命名を見直し変更しました。

2023-10-27 04:46 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +        static void Main(string[] args) {
ご質問ありがとうございます。OrderBy(x => x)に変更し、全体でアルファベット順になるよう変更いたしました。

2023-10-27 04:57 UTC, kurosu-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wNum = wWhere.Select(s => s.Length);
Firstメソッドでは、シーケンスに条件に一致する要素がなかった時例外をスローしますが、
FirstOrDefaultメソッドでは規定値を返します。
条件を検索する場面では、例外を発生させない為にFirstOrDefaultメソッドを使うのが適当だと考えました。

2023-10-27 06:50 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-4/Program3-2-4.cs
> +            var wNum = wWhere.Select(s => s.Length);
ばっちりですね！
すでに森田さんの指摘があってのFirstOrDefault()だったんですね。
空文字`""`のときに例外が起こることも理解されているようでよかったです！

2023-10-27 06:57 UTC, k-miyahara-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            Console.WriteLine(wMessage);
リストに存在しないとき、「-1」と表示されてもユーザーは何がなんだか分からないと思います。
対話型の場合は、ユーザーが迷わないようにすることが大切です。
メッセージを考えて書き直してみましょう！

2023-10-27 07:45 UTC, kurosu-being commented on 章末問題3/Practice3-2-1/Program3-2-1.cs
> +            Console.WriteLine(wMessage);
承知しました。
「その都市は登録されていません」にメッセージを変更いたしました。

2023-10-27 07:57 UTC, k-miyahara-being approved these changes
OKです！

2023-10-27 07:59 UTC, closed without merging