#458174 [C#テキスト]5章演習問題
kurosu-being/TextC pull request #6
Opened 2023-11-01 05:34 UTC by kurosu-being

第5章　文字列の操作

1.文字列同士の比較
2.文字列の変換
3文字列の判定
4.文字列の抽出
など、Stringクラスの使用方法を中心に、代表的な文字列操作について学習しました。

2023-11-01 09:47 UTC, ko-kato-being requested changes
ざっとレビューしてみました。
確認お願いします。

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "一致しています" : "不一致です。\n或いは入力された文字列の数が指定と違います";
メッセージの構築を1行で行ってしまうとは、なかなかやりますね 笑
コードを簡潔に記述しようとする意識は素晴らしいです。
ただ、今回は複数行に分けた方が可読性が高まるかなと思いました。

三項演算子を使う時は注意した方が良いです。
個人的には、三項演算子の分岐でさらに三項演算子を使う場合、可読性が落ちるケースが多いと思っています。

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "一致しています" : "不一致です。\n或いは入力された文字列の数が指定と違います";
「不一致」だったのか「指定数と異なる」だったのか、どちらか判別できた方がユーザーにとって親切かなと思います。

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "入力が空です。文字列を入力してください。" : (wInput.Split(',').Length == 2 && string.Compare(wInput.Split(',')[0], wInput.Split(',')[1], true) == 0)
`wInput.Split()`  の処理が何度も実行されているのが気になりました。
たぶん無駄なインスタンスを生成しないよう意識してくれたと思います。
その意識は素晴らしいです。
ただ、今回は`wInput.Split()`の戻り値を変数に格納した方が良いかと思います。
その後の処理で必要なもので、無駄ではありませんので。

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +       Practice5-3-1 空文字が何文字あるかカウントしてください　*/
「空文字」だと、処理と合っていないような気がしますね。
「空白」の数をカウントしたい？

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-3-4/Program5-3-4.cs
> +            foreach (var wWord in wUnderFourWords) {
`wUnderFourWords`の変数は不要かと思います。
foreach のコレクションとして直接指定するのが良いかと。

IEnumerable型の変数は宣言しない方が良いと思います。
遅延評価による副作用もありますので。
https://dev-redmine.being.group/projects/clgaia/wiki/IEnumerableの評価

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
> +            var wStringBuilderObject = new StringBuilder();
変数名を考える時に、その変数のスコープを意識すると良いです。
スコープとは、その変数を参照できる範囲のことです。
スコープが大きい場合は、いろんなところから参照されることになるので、ある程度具体的な名前が良いです。
逆に、今回のようにスコープが小さい時は、前後の文脈も把握していることを前提にして、簡易的な名前にしてしまっても良いと思います。
私なら、`wBuilder` にしますかね。

2023-11-01 09:47 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1/Program5-4-1.cs
> +        }
正規表現が正しいか判定できるツールが世の中にはあったりします。
たとえば、↓とか。
https://dev-redmine.being.group/projects/sirius-client/wiki/ツールの便利な使い方#DevToys

不安ならこういうツールを使っても良いかもしれないですね。

ちなみに、私は正規表現を使わずに、Splitを二重に行うかなと思いました。

2023-11-02 04:17 UTC, m-hotta-being requested changes
ちょっと見てみました。

2023-11-02 04:17 UTC, m-hotta-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            Console.WriteLine("[○○,■■」という形で2つの文字列を入力してください");
本筋とは関係ないですが……。

これって `[」` であってます？
`「」` とか、 `[]` ではなく？
```
[○○,■■」
```

2023-11-02 04:17 UTC, m-hotta-being commented on 章末問題5/Practice5-2-1/Program5-2-1.cs
> +                ?$"カンマ付きの数字文字列:{wNumber.ToString("#,0")}" : "無効な数字です。";
細かいスタイルの話ですが、空白が抜けてます。

```
?$"カンマ付きの数字文字列
```
↓
```
? $"カンマ付きの数字文字列
```

2023-11-02 04:17 UTC, m-hotta-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +       Practice5-3-1 空文字が何文字あるかカウントしてください　*/
それっぽいですね。テキストがおかしい？

2023-11-02 04:17 UTC, m-hotta-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
> +            var wStringBuilderObject = new StringBuilder();
`wSB` というのも見かけますね。

2023-11-02 05:19 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "一致しています" : "不一致です。\n或いは入力された文字列の数が指定と違います";
ご指摘ありがとうございます！
複数行に分ける記述に変更いたしました。
三項演算子を適切に使えるよう、三項演算子の分岐でさらに三項演算子を使うか判迷う場合は、
特に可読性を損なっていないか気を付けて判断したいと思います。

2023-11-02 05:20 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "一致しています" : "不一致です。\n或いは入力された文字列の数が指定と違います";
ご指摘ありがとうございます！
「不一致」だったのか「指定数と異なる」だったのか、ユーザーがどちらか判別できるように変更いたしました。

2023-11-02 05:28 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +                ? "入力が空です。文字列を入力してください。" : (wInput.Split(',').Length == 2 && string.Compare(wInput.Split(',')[0], wInput.Split(',')[1], true) == 0)
ご指摘ありがとうございます！
`string[] wInputArray = wInput.Split(',');`　を追加し、wInput.Split()の処理が何度も出てこないように変更いたしました。
同じ処理を何度も書いている時は特に気を付けた方が良いですね。

2023-11-02 05:28 UTC, kurosu-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +       Practice5-3-1 空文字が何文字あるかカウントしてください　*/
ご指摘ありがとうございます！
問題文を書き違えていました。「空白が何文字あるかカウントしてください」が正しい問題文です。
問題文の書き写し間違いがないかの確認を強化したいと思います。

2023-11-02 05:30 UTC, kurosu-being commented on 章末問題5/Practice5-3-4/Program5-3-4.cs
> +            foreach (var wWord in wUnderFourWords) {
ご指摘ありがとうございます！
直接foreach のコレクションとして直接指定する形に変更しました。
遅延評価について改めて勉強しなおしました。直接値が必要な場所に書くことで
遅延評価による副作用を回避している、という認識で正しいでしょうか・・・？

2023-11-02 05:31 UTC, kurosu-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
> +            var wStringBuilderObject = new StringBuilder();
@ko-kato-being  @m-hotta-being  
ありがとうございます！
wStringBuilderObject→wBuilderに変更いたしました。
wSBというのも良く使われるのですね。皆さんがどういった命名をされるのか見る機会が少ないので助かります🙇‍♀️

未だに変数の命名で悩みがちですが、スコープを意識したことはなかったです。
全体からみて分かりやすい、という評価だけだと現状どうしても長文の命名になってしまうので
スコープが小さいか大きいかの判断でも命名を行いたいと思います。

2023-11-02 05:31 UTC, kurosu-being commented on 章末問題5/Practice5-4-1/Program5-4-1.cs
> +        }
ご指摘ありがとうございます！
紹介していただいたDevToysを使って確認すると分かりやすかったです！ありがとうございます。
正規表現以外でも様々な変換やテキスト確認に対応していて面白いですね。

また、章の学習内容的にSplitを使うことを意図していると思うので、Practice5-4-1-SplitにSplitを二重に行う方法で新しく書き直してみました。

2023-11-02 05:31 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            Console.WriteLine("[○○,■■」という形で2つの文字列を入力してください");
ご指摘ありがとうございます！
修正しました。もっと目を凝らして確認します😇

2023-11-02 05:32 UTC, kurosu-being commented on 章末問題5/Practice5-2-1/Program5-2-1.cs
> +                ?$"カンマ付きの数字文字列:{wNumber.ToString("#,0")}" : "無効な数字です。";
ご指摘ありがとうございます！
空白を足して修正しました。

2023-11-06 08:29 UTC, ko-kato-being requested changes

2023-11-06 08:29 UTC, ko-kato-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            else{
少しだけフォーマットがおかしいですね。
コーディング規約的には↓のように書くのが正解です。
`} else {`

2023-11-06 08:29 UTC, ko-kato-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +       Practice5-3-1 空文字が何文字あるかカウントしてください　*/
「空白」の数のカウントですね、了解です！
全角の空白「　」はカウントしないですか？
指定した文字が空白かどうかを判定してくれるメソッドがあると思いますので、そちらを使ってみても良いかもしれないですね。

2023-11-06 08:29 UTC, ko-kato-being commented on 章末問題5/Practice5-3-4/Program5-3-4.cs
> +            foreach (var wWord in wUnderFourWords) {
> また、遅延評価について改めて勉強しなおしました。直接値が必要な場所に書くことで
> 遅延評価の値が必要な時に呼ばれる、という性質の副作用を回避している、という認識で正しいでしょうか・・・？
そうですね、イメージとしては良いと思います。
値が評価されるまでの間に意図しないコードが入り込む余地が無くなる、ということですね。

2023-11-06 08:29 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1-Split/Program5-4-1-Split.cs
新しいファイルに書いてくれたんですが、Program5-4-1.cs の中で、メソッドを分けるだけでも良いかなと思います。
追加のお題ですが、Novelistクラスを作ってみても良いかもですね。
```
static void Main(string[] args) {
    string wSentence = "Novelist=谷崎潤一郎;BestWork=春琴抄;Born=1886";
    var wNovelist = new Novelist(wSentence);

    Console.WriteLine($"作家  : {wNovelist.○○}");
    Console.WriteLine($"代表作: {wNovelist.○○}");
    Console.WriteLine($"誕生年: {wNovelist.○○}年");
}
```
↑のコードを実行できるようにNovelistクラスを作ってみてください。
wNovelist.○○ はプロパティ名ですので、適切な名前を考えてみてください。

2023-11-06 08:56 UTC, m-hotta-being approved these changes
修正ありがとうございます。
良いと思います。

[Wiki の 4. Visual Studio の設定を統一する](https://dev-redmine.being.group/projects/sirius-client/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%81%AE%E6%A7%8B%E7%AF%89%E6%89%8B%E9%A0%86#4-Visual-Studio-%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%82%92%E7%B5%B1%E4%B8%80%E3%81%99%E3%82%8B) とかって研修ではどうしてるんでしょう？まだ入れてないでしょうか？
フォーマットはツールに任せてしまったほうが、本当に重要なところに集中できてよいと思います。

もし何のことか分からなければ 宮原さん とか近くの先輩に聞いてみてください。

2023-11-06 08:56 UTC, m-hotta-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
【ただのコメント、修正不要です】
* 読み取り箇所が 1 箇所しかない変数を作らない。

なんてことを試しにやってみると、また違った書き方の模索ができると思います。
やり過ぎると読みにくくなりますが、そういった書き方がされたコードも読めるように、練習してみると良いと思います。

2023-11-06 09:01 UTC, ko-kato-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
便乗して。
無駄な変数を作らないことによって、変数名を考えなくて良いというメリットもありますねー。

2023-11-07 01:24 UTC, kurosu-being commented on 章末問題5/Practice5-4-1-Split/Program5-4-1-Split.cs
ご指摘、ご教示いただきありがとうございます！

①「空白」のカウントについて
全角の空白「　」もカウントするように修正いたしました。
②遅延評価について
ご教示ありがとうございます！途中で意図しないコードが割りこむと、こちらの想定していない値に変更されることがあるのですね。実際にコードを書きながら勉強出来ました。ありがとうございます！
③追加のお題
ご指摘ありがとうございます！
復習の際に初めに自分がどう考えたのか、最初の状態を残しておきたかったのでファイルを分けました。見ずらいようでしたら再度修正いたします🙇‍♀️
追加のお題もありがとうございます！
Practice5-4-1-Splitに追加いたしました。（ちょうど次章でDictionaryについてだったので、Key、Valueの扱い方について勉強になりました）

2023-11-07 01:46 UTC, kurosu-being commented on 章末問題5/Practice5-4-1-Split/Program5-4-1-Split.cs
ご指摘、ご教示いただきありがとうございます！

①「空白」のカウントについて
全角の空白「　」もカウントするように修正いたしました。
②遅延評価について
ご教示ありがとうございます！途中で意図しないコードが割りこむと、こちらの想定していない値に変更されることがあるのですね。実際にコードを書きながら勉強出来ました。
③追加のお題
ご指摘ありがとうございます！
復習の際に初めに自分がどう考えたのか、最初の状態を残しておきたかったのでファイルを分けました。見づらいようでしたら再度修正いたします🙇‍♀️
追加のお題もありがとうございます！
Practice5-4-1-Splitに追加いたしました。（ちょうど次章でDictionaryについてだったので、Key、Valueの扱い方について勉強になりました）

2023-11-07 01:47 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            else{
ご指摘ありがとうございます！
正しいフォーマットになるよう修正いたしました。

2023-11-07 02:14 UTC, kurosu-being commented on 章末問題5/Practice5-3-5/Program5-3-5.cs
ご教示ありがとうございます！
Wiki の 4. Visual Studio の設定については、後日宮原さんからインポートするファイルを配布して頂く予定です。
どういったフォーマットなのか把握しつつ、ツールを使用していこうと思います。

> - 読み取り箇所が 1 箇所しかない変数を作らない。
> 
> なんてことを試しにやってみると、また違った書き方の模索ができると思います。
ありがとうございます！省略すべき変数かどうかの判断において検討していきます。

2023-11-07 08:57 UTC, ko-kato-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            else{
修正ありがとうございました。
`} else{`
惜しいです、非常に細かいのですが、else の後に空白が必要です。
設定ファイルもらうってことなんで、自動整形機能を使っていくと良いですね。

2023-11-07 09:37 UTC, ko-kato-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +        }
char.IsWhiteSpace() を使うことによって、様々な「空白」に対応することができましたね、素晴らしい！
空白とはそもそも何なのか、調べていくと「文字コード」というワードが出てくると思います。
開発してるとたまにこの言葉に遭遇すると思いますので、時間のある時にどういうものなのか調べてみると良いかもしれません。
(すでにバッチリですかね？😇)

ちなみにですが、既存のCount()メソッドを使わずに、新たにメソッドを作ったのは理由があったりしますか？

2023-11-07 09:37 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +                this.Born = wBornYear;
Born は int 型のプロパティにしたんですね。
とても良いと思います！
プログラミング始めて間もないと、string型で受けとったからstring型の変数に格納するって、やっちゃいがちな気がしますが、黒子さんは筋が良いですね😊

parts がコーディング規約違反なのが惜しいです！

2023-11-07 09:37 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +        public int Born { get; private set; }
クラスにもコメントを書きましょう。
プロパティ名がちょっと微妙な気がしました。
「Writer」で表現したいのは作家の名前かなと思います。
私なら「Name」というプロパティ名にしそうです。
参考までに～。

あ、あと、コンストラクタでしか値を設定しないプロパティはセッターを省略できます。
こちらも参考までに！

2023-11-07 09:42 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1-Split/Program5-4-1-Split.cs
> 復習の際に初めに自分がどう考えたのか、最初の状態を残しておきたかったのでファイルを分けました。見づらいようでしたら再度修正いたします🙇‍♀️

了解です！
黒子さんのリポジトリですので、黒子さんが見やすい書き方にしてもらって構いません:smile:

ただし、プロジェクトに合流した時は注意が必要です。
不要なコードは残さないというのが基本です。
ソースコードはGit管理してますので、過去の状態を確認したい場合はコミットをさかのぼります。

2023-11-07 09:51 UTC, m-hotta-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +        public int Born { get; private set; }
> あ、あと、コンストラクタでしか値を設定しないプロパティはセッターを省略できます。

補足ですー。
`private set;` の有無で、たぶん思っているより挙動が大きく変わります。
試しに下記のメソッドを追加して、セッターを省略したり元に戻したりしてみてください。
セッターをなぜ省略するのかが少しわかるかもしれません。

```
public void SetWriter(string vName) {
    Writer = vName;
}
```

2023-11-08 04:05 UTC, kurosu-being commented on 章末問題5/Practice5-1-1/Program5-1-1.cs
> +            else{
確認不足でした、失礼いたしました。
再度修正を行いましたので、ご確認のほどよろしくお願いします🙇‍♀️

2023-11-08 04:05 UTC, kurosu-being commented on 章末問題5/Practice5-4-1-Split/Program5-4-1-Split.cs
> ただし、プロジェクトに合流した時は注意が必要です💡
> 不要なコードは残さないというのが基本です。
> ソースコードはGit管理してますので、過去の状態を確認したい場合はコミットをさかのぼります。

現状の私のコミットするタイミングが「キリが良い時にコミットする」という区切りであった為、
Git管理をしている利点を考えておりませんでした。
「状態を保存する」ことを考えれば、後に必要になる状態があればその時点でコミットを行い、
後に遡りやすいコメントを残すのが適切ですね。
プロジェクトに合流した際に不要なコードを残す癖が付かないよう、コメントの書き方やGitの扱いにも慣れていきたいと思います🙋‍♀️

2023-11-08 04:06 UTC, kurosu-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +        }
文字コードについてはIsWhiteSpaceメソッドを選択する際に調べましたが、Unicodeが最も網羅的に文字が扱えるからこれで行こうと考えた時点で検索をやめていました。改めて調べると他の符号化文字集合やUTF-8について知らないことが多そうです。これから学習を進めていこうと思います！

既存のCount()メソッドを使わなかった理由ですが、結論から申し上げますとリファクタリング不足です😇
（全角やTabの空白も削除するメソッドを用いた時、なんらかの条件分岐が発生するのではないかと考え、
　最初にメソッドの枠だけ用意してから書き始めましたが、必要ありませんでした。）
よって、Count()メソッドを用いて簡潔に書くよう修正を行いました。
お手数をおかけしますが、再度ご確認いただけると幸いです。

2023-11-08 04:06 UTC, kurosu-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +                this.Born = wBornYear;
ありがとうございます！💪
parts→wPartsに修正いたしました。

2023-11-08 04:06 UTC, kurosu-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +        public int Born { get; private set; }
@ko-kato-being 
ご質問ありがとうございます！
①クラスにコメントを追加
②プロパティ名をWriter→Nameに変更
③セッターの省略
を行いました。

> private set; の有無で、たぶん思っているより挙動が大きく変わります。
> 試しに下記のメソッドを追加して、セッターを省略したり元に戻したりしてみてください。

ありがとうございます！試してみると、セッターが無い状態であるとエラーメッセージでも「読み取り専用の為変更できない」という旨をしめしてくれ分かりやすかったです。
セッターをprivateにするかどうか、またはセッターが不要なのか判断する為に、メソッドで何か値を書き換えようとしているか、コンストラクタでしか値を設定しないプロパティかどうかの確認を行いたいと思います。

2023-11-08 05:21 UTC, ko-kato-being commented on 章末問題5/Practice5-3-1/Program5-3-1.cs
> +        }
修正ありがとうございます、OKです！
どういう経緯で作ったメソッドだったのか、とてもよくわかりました。
説明スキル高いねー:innocent:

2023-11-08 05:31 UTC, ko-kato-being commented on 章末問題5/Practice5-4-1-Split/Novelist.cs
> +        public int Born { get; private set; }
セッター非公開 < private < public の順にスコープは大きくなります。
基本的には最小のスコープにしておくのがおすすめです。
必要になった時にスコープを広げるのが良いと思います。
これは「YAGNI(やぐに)」という原則で、私は好きな考え方です:blush:

2023-11-09 02:26 UTC, merged