#459134 [C#テキスト]7章演習問題
kurosu-being/TextC pull request #8
Opened 2023-11-08 07:10 UTC by kurosu-being

第7章 配ディクショナリの操作

ディクショナリの操作（初期化、要素の格納方法、ディクショナリへの変換）について学習しました。

2023-11-09 08:44 UTC, r-nishiguchi-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        public string this[string vKey] => FDict.ContainsKey(vKey) ? FDict[vKey] : null;
Dictionaryからキーを使って値を取り出すとき、Gaiaの開発ではTryGetValue()が推奨されます。
記法は以下のように書きます。
```
FDIct.TryGetValue(vKey, out int wValue);
return wValue;
```
利点は以下です。
①戻り値がboolのため、vKeyがあればどうする。なければどうするということを決めることがでます
②vKeyがなかった場合、wValueにはデフォルトの値が入ってきます。
③FDict[vKey]でキーがFDictになかった場合のエラーを防ぐことができます。

2023-11-10 06:23 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        public string this[string vKey] => FDict.ContainsKey(vKey) ? FDict[vKey] : null;
ご指摘ありがとうございます！
TryGetValue()を使い、修正いたしました。
TryGetValue()で確実に値を取得するように書くことが商品のエラーを防ぐことに繋がるのですね。
勉強になります🙇‍♀️

2023-11-10 08:22 UTC, r-nishiguchi-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        public string this[string vKey] => FDict.ContainsKey(vKey) ? FDict[vKey] : null;
OKです

2023-11-10 08:22 UTC, r-nishiguchi-being approved these changes

2023-11-13 10:25 UTC, k-miyahara-being requested changes
ほぼOKです！
少し確認をお願いします。

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (char wCharacter in wInputString) {
元の文字列が上書きされてしまっています。
元の文字列は維持するようにしてください。

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +            }
この7行の処理は1行で実現することができます。
ToDictionary()を使った方法で書き換えてみてください。
（7-1-2の解答はそのままでよいです。）

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-1-2/Program7-1-2.cs
> +                }
ガード節を使ってみてください。

また、14行目はもう少しコンパクトに書けます。
常に1ずつ増える場合はインクリメントを使ったほうが、数字を書き換えられる等によるバグが埋め込みされづらくなります。
`wCharCount[wCharacter] = 1`も右辺の`1`だけで十分ですね。

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        /// <param name="vSubstring">日本語の位置</param>
日本語の"一部" ではないですかね？
記憶が定かじゃないですが、テキストが誤字っていたような…

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-2-3/Program7-2-3.cs
> +            }
ファイルが存在するかどうかのチェックとても良いです！
ここもガード節を使ってみましょう。

2023-11-13 10:25 UTC, k-miyahara-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
メソッドの役割が「該当の要素を取り出す」と「出力する」の2つになってしまっています。
例えば、取り出した要素を使って別の操作をしたい、取り出した要素の値を書き換えたいといったとき、
毎回余計な出力処理が行われてしまいます。

メソッドは役割がなるべくシンプルで、それ単体でどこからでも使いまわせるようになっていることが理想的です。

2023-11-15 06:31 UTC, kurosu-being commented on 章末問題7/Practice7-1-2/Program7-1-2.cs
> +                }
ご指摘ありがとうございます！
ガード節を使い修正いたしました。
インクリメントの前置後置がどちらかが怪しくかったので式で書いてしまいましたが、数字を書き換えられる等によるバグを埋め込まない為にも正しく理解したいと思います。

2023-11-15 06:31 UTC, kurosu-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +            }
ご指摘ありがとうございます！
ToDictionary()を使い、一行で処理を書き直しました。

2023-11-15 06:31 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        /// <param name="vSubstring">日本語の位置</param>
ご指摘ありがとうございます！
位置→一部に変更いたしました。
ニュアンスで位置ともいえるか・・・！？と己を納得させてしまいました😅

2023-11-15 06:31 UTC, kurosu-being commented on 章末問題7/Practice7-2-3/Program7-2-3.cs
> +            }
ありがとうございます！💪
ガード節を使いファイルが存在しない場合早期に処理を返すように修正しました。

2023-11-15 06:31 UTC, kurosu-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
ご指摘ありがとうございます！
メソッドの機能が単機能になるようにDisplayThreeメソッド修正しました。

> メソッドは役割がなるべくシンプルで、それ単体でどこからでも使いまわせるようになっていることが理想的です。
どこまでが単機能かが分かりづらいと感じていたのですが、それ単体でどこからでも使いまわせるという観点がありませんでした。勉強になります！

2023-11-16 02:22 UTC, kurosu-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +            foreach (char wCharacter in wInputString) {
ご指摘ありがとうございます。
foreachの中でwInputString.ToUpper()を直接渡す形に変更し、元の文を書き換えないよう修正いたしました。

2023-11-20 06:52 UTC, k-miyahara-being commented on 章末問題7/Practice7-2-3/Program7-2-3.cs
> +                Console.WriteLine($"削除後の要素の数: {wCount}");
インデントがずれています。

2023-11-20 06:52 UTC, k-miyahara-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
メソッドの機能にあわせて、命名も変えられているのでGoodです！

2023-11-20 07:01 UTC, kurosu-being commented on 章末問題7/Practice7-2-3/Program7-2-3.cs
> +                Console.WriteLine($"削除後の要素の数: {wCount}");
失礼しました。コード整形をして修正いたしました。
コード整形の確認をさらに強化します。

2023-11-20 07:23 UTC, k-miyahara-being approved these changes
OKです！

2023-11-20 10:49 UTC, yuki-tanaka-being reviewed
レビューしました。
ご確認お願いします。

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +                Console.WriteLine($"'{wKeyValuePair.Key}':{wKeyValuePair.Value}");
本題とは逸れますが、[`KeyValuePair<TKey, TValue>`](https://learn.microsoft.com/ja-jp/dotnet/api/system.collections.generic.keyvaluepair-2?view=netframework-4.7.2) は [分解](https://learn.microsoft.com/ja-jp/dotnet/csharp/fundamentals/functional/deconstruct) という書き方ができます。
```csharp
foreach ((char wChar, int wCount) in wCharCount.OrderBy(x => x.Key)) {
    Console.WriteLine($"'{wChar}':{wCount}");
}
```
まだ学習してないかもですが、タプルと呼ばれるものを扱うときに知っていると便利です。
利点は、簡単に分かりやすく変数名を付けられることです。
[未確認飛行 C - 複合型の分解](https://ufcpp.net/study/csharp/datatype/deconstruction/#deconstruction) のさわり部分を読むと便利さがわかるかと思います。
タプルに限らず KeyValuePair も Key とか Value って結局何が入っているの？というのが変数名を付けることで分かりやすくなります。

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
初期化以外でインスタンスを変更しないクラス変数は `readonly` を付けるとバグを埋め込みにくい堅牢なプログラムになります。

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
Dictionary の変数名は KeyToValue がおすすめです。
Key と Value 部分は、実際に何が入るかを入れます。
例えば、ユーザーIDがキーでユーザー名が値だった場合、`IDToName` みたいな感じです。
変数名から Key と Value が何か分かるようになり、コード全体の可読性が上がるのと、バグを埋め込みにくくなります。

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +                return wValue;
レビューで TryGetValue を使う方法を教えてもらっているかと思いますが、こちらも一行で書くことができます。
`public string this[string vKey] => FDict.TryGetValue(vKey, out string wValue) ? wValue : null;`
良くある書き方なので、覚えておいて損はないです！

ちなみに、TryGetValue の戻り値の bool を使わないコードがあったら、キーが無い時の考慮が漏れているか、すでにキーがあることが保証されており TryGetValue を使う必要性がないか、のどちらかを疑うとよいです。

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        }
メソッドを利用する側のことを考えると、戻り値の方は `KeyValuePair<string, string>` ではなく、`(string Abbreviation, string Japanese)` のタプルが使いやすいです。
型をみるだけで、戻り値が何か分かるので可読性がよいです。
また、分解せずにタプルのまま変数に取った場合も、`x.Abbreviation` と `x.Japanese` となるので分かりやすいです。
KeyValuePair だと、`x.Key` と `x.Value` となり、抽象度が高くて何かわからないです。

---

可読性の話を幾つか書いていますが、プログラムにおけるコードの表現力に着目すると面白いです。
コメントではなく、如何にコードで他者へ意図を伝えられるかを意識してみてください。
コードだけで意図を表現できる場所ってそもそもどこだろうか？
メソッド名、引数の型、引数名、戻り値の型、変数名、アルゴリズム、など沢山あります。
一つ一つは些細なものもありますが、すべてに意味を込めて書かれたコードと、まったく意識していないコードとでは、読みやすさが段違いになります。
まずは、沢山の表現の仕方を吸収するところから始めるのがよいです。
まずは、アウトプットよりインプット重視！

2023-11-20 10:49 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-3/Abbreviations.cs
> +        }
`Abbreviations` クラスから [I/O](https://e-words.jp/w/I-O.html) 処理を分割すると、[単一責任](https://ja.wikipedia.org/wiki/%E5%8D%98%E4%B8%80%E8%B2%AC%E4%BB%BB%E3%81%AE%E5%8E%9F%E5%89%87) のクラスになります。
本を読んでいないので今回のお題に反しているかもしれませんが、製品コードを書くなら気にした方がよい話になります。

ここでの I/O 処理は、コンストラクタでファイルパスを受け取って、ファイルから文字列を読み取っている処理です。
現在の `Abbreviations` を使うには、ファイルからテキストを読み取ることが強要されます。
もし、単純に省略語と日本語の辞書というクラスが使いたいだけの人がいた場合、必ずファイルから生成することが強いられます。つらいです。
もし、.NET 標準の Dictionary クラスを new するのに、必ずファイルからデータを取ってくる必要があった場合を想像してみてください。つらいです。
というお話になります。

じゃあ空のコンストラクタも用意すれば解決するかというと、それも違います。
ファイルからではなくネットワーク経由で初期データを用意したい要求がでてきた場合を想像してみてください。
コンストラクタを増やすか？
それでも対応はできますが、初期化方法が増える度にクラスが肥大化していきます。
しかも本来の、辞書としての役割には全く関係ない部分で変わります。
単一責任のクラスにすることで、複雑度が下がり、メンテナンスしやすいコードになります。

解決策は、シンプルに  I/O 処理を外に出して、`Abbreviations` クラスは、引数なしのコンストラクタと、初期化時にデータをセットできるように `IDictionary<TKey,TValue>` を引数に取るコンストラクタを実装します。
オブジェクト内のデータは、使う側が自由に設定できるようにします。

2023-11-22 02:35 UTC, kurosu-being commented
GitHubのテストです（演習問題とは無関係です）
[リンク](https://qiita.com/RyotaMurohoshi/items/dda4b2d623ddc9e0f6ff#:~:text=Deconstruct%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8CKeyValuePair%3CTKey%2C%20Tvalue%3E%E3%81%AA%E3%81%A9%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%81%A6%E3%80%81ValueTuple%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB%E5%88%86%E8%A7%A3%E5%AE%A3%E8%A8%80%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8B%20C%23.NET%20Last%20updated%20at%202019-03-02%20Posted,%E3%81%95%E3%81%A6%E3%80%81%E3%81%93%E3%81%AE%E5%88%86%E8%A7%A3%E3%81%A7%E3%81%99%E3%81%8C%20ValueTuple%20%E5%9E%8B%E3%81%A7%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%20Deconstruct%20%E3%81%A8%E3%81%84%E3%81%86%E5%90%8D%E5%89%8D%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8B%E6%8B%A1%E5%BC%B5%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92%E6%8C%81%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8C%E3%81%B0%E4%BD%BF%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82%20%E6%A8%99%E6%BA%96%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E5%9E%8B%E3%81%AB%20Deconstruct%20%E3%81%A8%E3%81%84%E3%81%86%E5%90%8D%E5%89%8D%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%80%81%E3%82%82%E3%81%97%E3%81%8F%E3%81%AF%E6%8B%A1%E5%BC%B5%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8C%E5%8A%A0%E3%82%8F%E3%82%8A%E5%88%86%E8%A7%A3%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82)

2023-11-22 06:25 UTC, kurosu-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +                Console.WriteLine($"'{wKeyValuePair.Key}':{wKeyValuePair.Value}");
ありがとうございます！
分解という書き方は初めて知りましたが、タプルを使うとKeyValuePair のKeyとValueがコード上で明確になり、以前アドバイス頂いた「コードだけで理解できる」という点が大きく改善されますね！

自分でも使ってみたいと思いコードを書きなおそうとしたのですが、ご提示いただいたコードを使用すると

> 'KeyValuePair<char, int>' に 'Deconstruct' の定義が含まれておらず、型 'KeyValuePair<char, int>' の最初の引数を受け付けるアクセス可能な拡張メソッド 'Deconstruct' が見つかりませんでした。
というエラーメッセージが出ました。
そこで2点質問があります。

①これを解消する為にはどのようにコードを変更すればよいのでしょうか？
②このエラーの原因を「使用している.NET Frameworkではまだ 'KeyValuePair<char, int>' に 'Deconstruct' の定義が実装されていない為使うことが出来ない」と考えたのですが、これは正しいのでしょうか？
（こちらに関してはこの[サイト](https://qiita.com/RyotaMurohoshi/items/dda4b2d623ddc9e0f6ff#:~:text=Deconstruct%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8CKeyValuePair%3CTKey%2C%20Tvalue%3E%E3%81%AA%E3%81%A9%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%81%A6%E3%80%81ValueTuple%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB%E5%88%86%E8%A7%A3%E5%AE%A3%E8%A8%80%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8B%20C%23.NET%20Last%20updated%20at%202019-03-02%20Posted,%E3%81%95%E3%81%A6%E3%80%81%E3%81%93%E3%81%AE%E5%88%86%E8%A7%A3%E3%81%A7%E3%81%99%E3%81%8C%20ValueTuple%20%E5%9E%8B%E3%81%A7%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%20Deconstruct%20%E3%81%A8%E3%81%84%E3%81%86%E5%90%8D%E5%89%8D%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8B%E6%8B%A1%E5%BC%B5%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92%E6%8C%81%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8C%E3%81%B0%E4%BD%BF%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82%20%E6%A8%99%E6%BA%96%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E5%9E%8B%E3%81%AB%20Deconstruct%20%E3%81%A8%E3%81%84%E3%81%86%E5%90%8D%E5%89%8D%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%80%81%E3%82%82%E3%81%97%E3%81%8F%E3%81%AF%E6%8B%A1%E5%BC%B5%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8C%E5%8A%A0%E3%82%8F%E3%82%8A%E5%88%86%E8%A7%A3%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82)を見て結論付けました）

お忙しいところ恐縮ですが、 ご教授いただけると幸いです🙇‍♀️

2023-11-22 07:10 UTC, kurosu-being commented on 章末問題7/Practice7-2-3/Abbreviations.cs
> +        }
ご指摘ありがとうございます！
Practice7-2-3において、Abbreviations クラスに空のコンストラクタとIDictionary<TKey,TValue> を引数に取るコンストラクタに変更いたしました。
（汎用的なコードになるようにDictionary<TKey, TValue> ではなくIDictionary<TKey,TValue>を引数にとるのは以前もご指摘頂いた部分ですね😀）
コンストラクタに何を設定すべきか、製品として利用する時どういうことがおこりそうかなど、先輩方に解説頂きながら沢山勉強になりました。ありがとうございます！

2023-11-22 07:10 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +                return wValue;
ご指摘ありがとうございます！
ご提示いただいたコードで修正いたしました。
TryGetValueや他の戻り値がbool型のメソッドについて、考慮が漏れていないか特に注意したいと思います。

2023-11-22 07:10 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
ご指摘ありがとうございます！
FDictをwAbbraviationToJapaneseに変更いたしました。
（長い名前ですが、スコープの広いフィールド変数なので分かりやすさの方を重視すべきと判断しました）

2023-11-22 07:10 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
ご指摘ありがとうございます！
readonlyを付け修正いたしました。

2023-11-22 07:27 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        }
ご指摘ありがとうございます！
タプルの扱いについて分かり次第こちらも修正したいと思います。

> メソッド名、引数の型、引数名、戻り値の型、変数名、アルゴリズム、など沢山あります。
> 一つ一つは些細なものもありますが、すべてに意味を込めて書かれたコードと、まったく意識していないコードとでは、読みやすさが段違いになります。
同じことではないかもしれませんが、同じ機能だからとコピペで切り貼りしたコードと、一から必要だと思いながら書いたコードでは読みやすさが全然違うと感じます。一行一行がコンピューターへの命令と思って意味を込めるのが大切ですね。

> まずは、沢山の表現の仕方を吸収するところから始めるのがよいです。
> まずは、アウトプットよりインプット重視！
書籍や先輩方のレビューから吸収すべく頑張ります！💪

2023-11-22 09:32 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
修正ありがとうございます！
動作的に問題はありませんが、記載する順番は `private readonly` が一般的かなと思います。
更に static を付ける場合は `private static readonly` の順番になります。
製品コードを書く時は、周りの実装見ながら真似ればよいです！

2023-11-22 09:34 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
コードは問題ないですが、ここの投稿だけ `w` 始まりになってますね😂

2023-11-24 01:25 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
失礼しました😱コメントを修正いたしました。

2023-11-24 01:28 UTC, kurosu-being commented on 章末問題7/Practice7-2-1/Abbreviations.cs
> +        private Dictionary<string, string> FDict = new Dictionary<string, string>();
ご指摘ありがとうございます！
記載する順番を修正いたしました。
フォーマットを守ることもコードの可読性には重要ですね。
製品コードや他者のコードに手を加えるときなど、周りの実装を真似るように心がけたいと思います。

2023-11-24 05:51 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +                Console.WriteLine($"'{wKeyValuePair.Key}':{wKeyValuePair.Value}");
ごめんなさい。調べてもらった通りでした。
KeyValuePair の分解は、.NET Core 2.0 以上からじゃないと標準サポ―トしていませんでした。
タプルの分解は、C# 7 以降から対応しているので使えます。

KeyValuePair の分解を .NET Core 2.0 未満で使う方法ですが、以下のクラスとメソッドを用意して、使いたいクラスで参照できるようにしておけば使えるようになります。
```csharp
    public static class KeyValuePairExtensions {

        /// <summary>
        /// 分解構文を有効にします。
        /// </summary>
        /// <example>
        /// <code><![CDATA[
        /// foreach ((int wCD, string wName) in wDictionary) {
        /// }
        /// ]]></code>
        /// </example>
        public static void Deconstruct<TKey, TValue>(this KeyValuePair<TKey, TValue> vPair, out TKey vKey, out TValue vValue) {
            vKey = vPair.Key;
            vValue = vPair.Value;
        }
    }
```
標準で用意されていないだけで、自前で実装すれば使えるようになります。
Gaia Cloudのソースには、この実装が含まれていたので使えていただけでした😂

2023-11-24 06:35 UTC, yuki-tanaka-being reviewed
なぜか 7.2.4 を見ていなかったので追加でレビューしました。
ご確認お願いします。

2023-11-24 06:35 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
メソッド名の付け方について、確定したコレクションを返すか、遅延評価される列挙を返すか、で異なる表現をするのがおすすめです。
列挙を返すのに `GetXXX` は使わない方がよいです。代わりに `EnumerateXXX` などを使います。
Get は一般的に定まっているものを返すイメージです。
また、`IEnumerable<T>` を返すならすべて `EnumerateXXX` でもないので注意です。
（列挙を受け取って特定の条件でフィルタリングした列挙を返すメソッドなら Filter など）

■参考
* [Directory.EnumerateFiles メソッド](https://learn.microsoft.com/ja-jp/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.7.2)
* [Directory.GetFiles メソッド](https://learn.microsoft.com/ja-jp/dotnet/api/system.io.directory.getfiles?view=netframework-4.7.2)

どちらも指定したフォルダ内のファイル情報を返してくれメソッドですが、戻り値の型でメソッド名が異なるのが分かるかと思います。
理由もあります。上記のDirectoryクラスを例にします。
すべてのファイル情報が欲しいならどちらを使っても大差ないです。
もし、特定のファイル名を含むものがあるか知りたいとした場合、EnumerateFiles の方は見つかった時点で、残りのファイルは一切参照しません。
GetFiles の方は、最初にすべてのファイル情報へアクセスします。
もし、フォルダ内に数万ファイルあったとして、どちらがパフォーマンスが良いか考えると、EnumerateFiles の方が期待値が高いです。
そういった動作の違いが、メソッド名だけで使う側に分かるようになっているのが利点です。
ちゃんと遅延評価されているというのが分かるのもポイントです。
※フォルダ内のファイルを参照する処理内で、ファイルを追加するような処理が入る場合、遅延評価は正しく動作しません。（.NET だと実行時エラーが発生するはずです）
　先に、全ファイル情報を取得してからループを回す必要があります。

2023-11-24 06:37 UTC, kurosu-being commented on 章末問題7/Practice7-1-1/Program7-1-1.cs
> +                Console.WriteLine($"'{wKeyValuePair.Key}':{wKeyValuePair.Value}");
自身のVisualStudioでも正常に動作するのを確認できました！調べて頂きありがとうございます。
分解の書き方からGaia Cloudのソースについても知ることが出来て嬉しいです。扱えるようにクラスを用意してあったのですね😳サポートのバージョンで出来ることが増えたり、便利な書き方が出来るように拡張メソッドやクラスを追加していたりと、色んな方々のコードの可読性を上げていこうとする試みを垣間見た気がします。
ありがとうございます！

2023-11-24 06:41 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-3/Abbreviations.cs
> +        }
正しく実装できてますよー👍 
これで Abbreviations クラスは再利用しやすいものとなりました。

今度は逆に、ファイルを読み込んで Abbreviations クラスを生成する部分を main に書くことになりました。
main が I/O 処理を持つことになりましたが、今回はこれで構いません。
もし、この処理を使いまわしたくなった場合は、ファイルから Abbreviationsクラスを生成する役割をもつクラスを作成します。
そうすることで、生成とモデルを分離しつつ、どちらも再利用（組み合わせ）しやすいものが出来上がります。
プログラムが大きくなるにつれて、このようにリファクタリングをしていくことが大切になってきます。

2023-11-27 01:44 UTC, kurosu-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
ご指摘ありがとうございます！
GetThreeAbbr→EnumerateThreeAbbrに修正いたしました。
取得する戻り値が列挙型の時EnumerateXXXという名付けがセオリーであることは知りませんでした。
確かに、配列と列挙型は似ているようでコード上での振る舞い方が大きく異なる為、どちらなのか明示する方が便利ですね。
以後使っていきたいと思います！

2023-11-27 10:41 UTC, yuki-tanaka-being commented on 章末問題7/Practice7-2-4/Abbreviations.cs
> +        }
今回のお題に対しては今の実装で問題ありません。
クラス設計の観点では戻り値の型を `IEnumerable<(string, string)>` にしたり、省略語と日本語を変数に持つクラスを作成して `IEnumerable<newClass>` にする方のがおすすめです。
理由は、使う側からみて汎用性が高い方が使いやすく再利用性が高いからです。
例えば、このメソッドが2か所以上から呼ばれるとして、ある場所では `省略語=日本語` と表示したいし、別のある場所では `[省略語]: 日本語` と表示したいとなったときに、今の実装では対応できません。
メソッド側でフォーマットを構築してしまっているからです。
構造化されたデータに比べて文字列データは扱いづらくなってしまいます。
戻り値の型を決める際にぜひ思い出してみてください。

2023-11-29 02:16 UTC, merged