#456921 [C#テキスト]4章演習問題
kurosu-being/TextC pull request #9
Opened 2023-11-10 06:57 UTC by kurosu-being

第8章　日付、時刻の操作

DateTime構造体を中心に日付と時刻の操作を学習しました。

2023-11-10 09:07 UTC, yuki-tanaka-being commented on 章末問題8/Practice8-3-1/TimeWatch.cs
問題の意図が読めていないですが、`TimeWatch` は `DateTime` を使って実装するお題かと思いました。
`Stopwatch` みたいなクラスを自分で実装してみなさいということかな？
余裕があれば、`DateTime` を使って実装するパターンも挑戦してはいかがでしょうか。

---

あとは、指示通りなら `TimeWatch` を new した時点でカウント開始かなと思います。
お題ではなくちゃんとしたストップウォッチを実装するなら、今回実装したように `Start` が別である方がよいと思います。

2023-11-20 06:47 UTC, kurosu-being commented on 章末問題8/Practice8-3-1/TimeWatch.cs
ご指摘ありがとうございます！
StopWatchにStopメソッドを再実装するなどおかしなところがあった為、テキスト本来の主旨であるDateTimeクラスを用いた方法で修正いたしました。
また、テキストの指示に沿うようにTimeWatchをnewした時点でカウントが開始されるように修正しました。

2023-11-20 08:50 UTC, yuki-tanaka-being commented on 章末問題8/Practice8-3-1/TimeWatch.cs
いいですね。
機能としては問題ありません。

より良い設計の観点でリファクタリングの提案です。
実行中という情報を DRY にできます。
※DRYについては、[IT用語辞典](https://e-words.jp/w/DRY%E5%8E%9F%E5%89%87.html) や [DRY原則](https://xn--97-273ae6a4irb6e2hsoiozc2g4b8082p.com/%E3%82%A8%E3%83%83%E3%82%BB%E3%82%A4/DRY%E5%8E%9F%E5%89%87/) を参照。
`FIsRunning` という変数が実行中という状態を表していますが、実際に実行中にするには開始時刻を保持する必要があります。
逆を言うと、開始時刻を持っていれば実行中であると言えます。
そうなると、実行中という状態が二つの変数で管理されていることになります。
この二つの変数は依存しており、必ずセットで扱わないと正しい状態を示さないことになってしまいます。
今は単純な実装なのでバグを埋め込む可能性は低いですが、コード量が多くなるにつれて複雑度が増していきます。

それを解消するために、状態を表現を1つのオブジェクトで行うようにします。
実現方法は `FStartTime` がデフォルト値なら未実行、それ以外なら実行中とするか、`FStartTime` を Null許容型にして null なら未実行、null 以外なら実行中とします。
デフォルト値の実装例は以下です。
```csharp
class TimeWatch {
    private DateTime FStartTime;
    private bool IsRunning => this.FStartTime != default;

    public TimeWatch() => this.Start();

    public void Start() {
        if (this.IsRunning) return;
        this.FStartTime = DateTime.Now;
    }

    public TimeSpan Stop() {
        try {
            if (!this.IsRunning) return TimeSpan.Zero;
            return DateTime.Now - this.FStartTime;
        } finally {
            this.FStartTime = default;
        }
    }
}
```
実装例のポイントは2つあります。
* `IsRunning` というプロパティを用意することで、実行中を DRY にします。
評価したい場所で都度 `this.FStartTime != default` とも書けますが、それだと状態の定義が記載場所に散らばあり、`FIsRunning` で管理していたころより状態管理の複雑度が上がってしまいます。
* `finally` にデフォルト値に戻す処理を書くことで、`Stop` メソッドが実行されたら必ず実行中でなくなるようにします。
もしエラーが起きても、オブジェクトの内部状態は可能な限り正しく保てるようにします。

2023-11-27 02:56 UTC, kurosu-being commented on 章末問題8/Practice8-3-1/TimeWatch.cs
ご指摘ありがとうございます！
ご提案いただいた方法で修正し、動作を確認しました。
（defaultの表記だけ、C#7.1以上の言語バージョンが必要とのことだったのでdefault→default(DateTime)と修正ました。現在使用しているC#言語バージョンは6.0のようです）
重複していたIsRunningとFStartTimeの役割を、依存関係を利用して重複を回避することが出来るのですね。
勉強になります✍

2023-11-29 02:17 UTC, k-miyahara-being requested changes

2023-11-29 02:17 UTC, k-miyahara-being commented on 章末問題8/Practice8-1-1/Program8-1-1.cs
> +            Console.WriteLine(wDate.ToString("f"));
1つめの表示形式の日付部分が満たせていないようです。
フォーマットを見直してみてください。

2023-11-29 02:17 UTC, k-miyahara-being commented on 章末問題8/Practice8-1-1/Program8-1-1.cs
> +            var wDayOfWeek = wCulture.DateTimeFormat.GetDayName(wDate.DayOfWeek);
ローカル変数の宣言は、使用する場所になるべく近いところで行うのがよいです。
メソッドの先頭で宣言された変数が、いろいろと処理を挟んだ後に末尾で使用されていると、
上から読んだときに余計な思考を生んでしまいます。

2023-11-29 02:17 UTC, k-miyahara-being commented on 章末問題8/Practice8-2-1/Program8-2-1.cs
> +            return vDate.AddDays(wDaysSpan + 7);
計算式を見直してみてください。
今日が水曜日として、指定曜日を月または火曜日にすると、再来週の日にちになってしまいます。

2023-11-29 05:18 UTC, kurosu-being commented on 章末問題8/Practice8-1-1/Program8-1-1.cs
> +            Console.WriteLine(wDate.ToString("f"));
ご指摘ありがとうございます！
正しいフォーマットで表示されるよう修正しました。

2023-11-29 05:18 UTC, kurosu-being commented on 章末問題8/Practice8-1-1/Program8-1-1.cs
> +            var wDayOfWeek = wCulture.DateTimeFormat.GetDayName(wDate.DayOfWeek);
ご指摘ありがとうございます！
変数の宣言位置を変更し、使用する場所と対応するよう修正しました。
出来るだけ狭い範囲でコードを確認できるようにする為にも、宣言の位置に気をつけたいと思います。

2023-11-29 05:18 UTC, kurosu-being commented on 章末問題8/Practice8-2-1/Program8-2-1.cs
> +            return vDate.AddDays(wDaysSpan + 7);
ご指摘ありがとうございます！
計算式を修正し、来週の曜日が出るように修正しました。
また、コード上で曜日を選択する方法をやめ、ユーザーが曜日を指定できるように変更いたしましたので、
ご確認いただけると幸いです。

2023-11-29 07:11 UTC, k-miyahara-being commented on 章末問題8/Practice8-2-1/Program8-2-1.cs
> +            return vDate.AddDays(wDaysSpan + 7);
こうしたらいいかも、を実際にやってみるのはとてもいいですね！
ぜひ今後も、学習のためにいろいろな実装を試してみてください👍

2023-11-29 07:17 UTC, merged